version: "3"

services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_USER: server
      MARIADB_PASSWORD: 1234
      MARIADB_DATABASE: server
      MARIADB_ROOT_PASSWORD: 1234
      MYSQL_TCP_PORT: 3306
      MYSQL_UNIX_PORT: 3306
    ports:
      - 3333:3306

  nginx:
    image: nginx:latest
    restart: always
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
