version: "3"

services:
  server-main:
    image: "442042508341.dkr.ecr.us-east-2.amazonaws.com/test-server-repository:latest"
    restart: always
    container_name: "server-main"
    ports:
      - "8080:8080"
    networks:
      - server-network

networks:
  server-network:
    driver: bridge
