spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3333/server?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: server
    password: 1234
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  jwt:
    key: your-jwt-key-your-jwt-key-your-jwt-key-your-jwt-key-your-jwt-key-your-jwt-key

logging:
  config: classpath:log4j2-local.yml

server:
  host: http://localhost
  client:
    url: http://localhost
    http-url: http://localhost
  cookie:
    domain: localhost
    name: access_token
    max-age: 604800000
    path: /
    http-only: false
    secure: false
    same-site: none
  jwt:
    common-token-expire-time: 604800000
    refresh-token-expire-time: 2592000000

swagger:
  base-url: http://localhost