name: Server CI

on:
  push:
    paths:
      - "server/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  server-CI:
    runs-on: ubuntu-latest
    steps:
      - name: 체크아웃
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "corretto"

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Gradle 빌드
        run: |
          mkdir -p src/main/resources/
          echo ${{ secrets.APPLICATION_PROD_YML }} | base64 -d > src/main/resources/application-prod.yml
          chmod +x gradlew
          ./gradlew build
        shell: bash

      # - name: Configure AWS credentials
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ap-northeast-2

      # - name: Upload build file to S3 and trigger CodeDeploy
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   run: |
      #     cp build/libs/*-*.jar deploy-main/
      #     mkdir -p deploy && cp -r deploy-main/* deploy/
      #     zip -r deploy.zip deploy

      #     aws s3 cp deploy.zip s3://${{ secrets.AWS_S3_DEPLOY_MAIN_BUCKET_NAME }}/deploy.zip

      #     aws deploy create-deployment \
      #     --application-name ${{ secrets.AWS_CODEDEPLOY_MAIN_APP_NAME }} \
      #     --deployment-config-name CodeDeployDefault.AllAtOnce \
      #     --deployment-group-name ${{ secrets.AWS_CODEDEPLOY_MAIN_GROUP_NAME }} \
      #     --file-exists-behavior OVERWRITE \
      #     --s3-location bucket=${{ secrets.AWS_S3_DEPLOY_MAIN_BUCKET_NAME }},bundleType=zip,key=deploy.zip
